#include<iostream>
#include<vector>
#include<algorithm>//for generate
 
using namespace std; 
  
int linearSearch(vector<int> v, int n, int value) 
{ 
    int i; 
    for (i = 0; i < n; i++) 
        if (v[i] == value) 
            return i; 
    return -1; 
} 

void fillByRandomNums(vector<int> &v){  
    // Generate n random numbers between 0 and 99 by lambda func and fill it in vector
    std::generate(v.begin(), v.end(), []() {
        return rand() % 100;
    });
    std::cout << "Random Number Generated by Lambda Function" << std::endl;
    for (int val : v)
        std::cout << val << std::endl;
}

int main()
{
    int n, value;
    std::cout << "Enter the number of integers and the value you search for" << endl;
    cin >> n >> value;

    std::vector<int> v(n);
    fillByRandomNums(v);
    int result = linearSearch(v, n, value); 
   (result == -1)? cout<<"Value is not present in array\n" 
                 : cout<<"Value is present at index " <<result <<endl; 
   return 0; 
} 
