//Sean Stepanik
#include<iostream>
#include<vector>
#include<algorithm>//for generate
 
using namespace std; 
  
int linearSearch(vector<int> v, int n, int value) 
{ 
    int i; 
    for (i = 0; i < n; i++) 
        if (v[i] == value) 
            return i; 
    return -1; 
} 

void randomArray(vector<int> &v){  
    std::generate(v.begin(), v.end(), []() { return rand() % 100;});
    std::cout << "Random Number Generated by Lambda Function" << std::endl;
    for (int num : v)
        std::cout << num << std::endl;
}

int main()
{
    int n, value;
    std::cout << "Enter the number of integers and the value you search for" << endl;
    cin >> n >> value;

    std::vector<int> v(n);
    randomArray(v);
    int result = linearSearch(v, n, value); 
    if (result == -1) { 
        cout<<"Value is not present in array\n";
    } else {
        cout<<"Value is present at index " << result << endl;
    }
    return 0; 
}